---
title: "Generate the temporal abundance variation of sampled population"
author: "Romain Lorrilliere"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE,error = FALSE)
```

```{r source}
source("c:/git/LPI_theoritical_test/functions/fun_dyn_pop.r")
source("c:/git/LPI_theoritical_test/functions/fun_samples.r")
```

# One population sampled

## One population dynamic

We generate the abundance variation of one population following an exponential function. 
Thus the population abundance at t time N_t is only according to :
N(t+1) = exp(r) * N(t)
N0

```{r the_funciton}
f_recursive_dyn_pop
```
```{r parm1}
r <- -0.005
r_var <- 0.0025
N <- 1000
demographic_stocha <- "poisson"

```

For example :
r in N(mean=`r r`,sd = `r r_var`)and N0 = `r N` and with demographic stochasticity simulated thanks a pick up in a Poisson distribution. 

```{r dyn1}
l <- f_make_pop_dyn(nb_pop = 1, N0_mean = N,r_mean = r, r_temporal_var = r_var,demo_var= demographic_stocha, fig="print")


```

